# Generated by Django 3.1.1 on 2021-05-15 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexblog', '0003_auto_20210515_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=500, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
