# Generated by Django 3.1.7 on 2021-04-10 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslides',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heroslides',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
