# Generated by Django 3.1.7 on 2021-04-10 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210410_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylogo',
            name='logo_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
