# Generated by Django 3.1.7 on 2021-04-10 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_companylogo_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylogo',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
