# Generated by Django 3.1.7 on 2021-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210410_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.CharField(default='Bsc (Hons) Computer Science', max_length=300),
        ),
    ]
