# Generated by Django 3.1.7 on 2021-05-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_review_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companylogo',
        ),
    ]
