# Generated by Django 3.1.1 on 2021-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslides',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='why_with_us',
            name='description',
            field=models.TextField(),
        ),
    ]
