# Generated by Django 3.1.7 on 2021-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_auto_20210512_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_level',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_level_I',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='english_proficiency',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='english_proficiency_I',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='english_proficiency_II',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='english_proficiency_III',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_img_title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_img_title_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_I',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_II',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_III',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_IV',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_V',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_VI',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='level_subject_name_VII',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_english_proficiency_I',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_english_proficiency_II',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='total_create',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='course',
            name='university_name',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
