# Generated by Django 3.1.7 on 2021-05-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_auto_20210513_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='academic_level',
            new_name='academic_level_des',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='english_proficiency',
            new_name='english_proficiency_des',
        ),
    ]
