# Generated by Django 3.1.7 on 2021-05-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_auto_20210513_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='academic_level_des',
            new_name='academic_level',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='english_proficiency_des',
            new_name='english_proficiency',
        ),
    ]
