# Generated by Django 3.1.7 on 2021-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0006_auto_20210513_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_create',
        ),
        migrations.AddField(
            model_name='course',
            name='total_credits',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
