# Generated by Django 3.1.7 on 2021-05-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0009_auto_20210513_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hero_img',
        ),
    ]
