# Generated by Django 3.1.7 on 2021-05-15 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0011_auto_20210515_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.IntegerField(default=4, help_text='value 4 to 6', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_level',
            field=models.IntegerField(default=4, help_text='value 4 to 6', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(4)]),
        ),
    ]
