# Generated by Django 3.1.7 on 2021-05-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='about',
        ),
    ]
